import z from "zod";

export const VoteSchema = z
  .object({
    model: z
      .string()
      .describe(
        "The unique identifier of the Ensemble LLM which generated this vote."
      ),
    ensemble_index: z
      .uint32()
      .describe("The index of the Ensemble LLM in the Ensemble."),
    flat_ensemble_index: z
      .uint32()
      .describe(
        "The flat index of the Ensemble LLM in the expanded Ensemble, accounting for counts."
      ),
    vote: z
      .array(z.number())
      .describe(
        "The vote generated by this Ensemble LLM. It is of the same length of the number of responses provided in the request. If the Ensemble LLM used logprobs, may be a probability distribution; otherwise, one of the responses will have a value of 1 and the rest 0."
      ),
    weight: z.number().describe("The weight assigned to this vote."),
    retry: z
      .boolean()
      .optional()
      .describe(
        "Whether this vote came from a previous Vector Completion which was retried. `from_cache` will also be `true`."
      ),
    from_cache: z
      .boolean()
      .optional()
      .describe(
        "Whether this vote came from the global ObjectiveAI votes cache."
      ),
    from_rng: z
      .boolean()
      .optional()
      .describe("Whether this vote was generated via RNG."),
  })
  .describe("A vote from an Ensemble LLM within a Vector Completion.");
export type Vote = z.infer<typeof VoteSchema>;

export namespace Vote {
  export function mergedList(a: Vote[], b: Vote[]): [Vote[], boolean] {
    let merged: Vote[] | undefined = undefined;
    for (const vote of b) {
      const existingIndex = a.findIndex(
        ({ flat_ensemble_index }) =>
          flat_ensemble_index === vote.flat_ensemble_index
      );
      if (existingIndex === -1) {
        if (merged === undefined) {
          merged = [...a, vote];
        } else {
          merged.push(vote);
        }
      }
    }
    return merged ? [merged, true] : [a, false];
  }
}

export const VotesSchema = z
  .array(VoteSchema)
  .describe(
    "The list of votes for responses in the request from the Ensemble LLMs within the provided Ensemble."
  );
export type Votes = z.infer<typeof VotesSchema>;
