import { merge } from "src/merge";
import z from "zod";
import { convert, type JSONSchema } from "../../../json_schema";

export const TopLogprobSchema = z
  .object({
    token: z.string().describe("The token string."),
    bytes: z
      .array(z.uint32())
      .optional()
      .nullable()
      .describe("The byte representation of the token."),
    logprob: z
      .number()
      .optional()
      .nullable()
      .describe("The log probability of the token."),
  })
  .describe("The log probability of a token in the list of top tokens.");
export type TopLogprob = z.infer<typeof TopLogprobSchema>;
export const TopLogprobJsonSchema: JSONSchema = convert(TopLogprobSchema);

export const LogprobSchema = z
  .object({
    token: z
      .string()
      .describe("The token string which was selected by the sampler."),
    bytes: z
      .array(z.uint32())
      .optional()
      .nullable()
      .describe(
        "The byte representation of the token which was selected by the sampler."
      ),
    logprob: z
      .number()
      .describe(
        "The log probability of the token which was selected by the sampler."
      ),
    top_logprobs: z
      .array(TopLogprobSchema)
      .describe("The log probabilities of the top tokens for this position."),
  })
  .describe(
    "The token which was selected by the sampler for this position as well as the logprobabilities of the top options."
  );
export type Logprob = z.infer<typeof LogprobSchema>;
export const LogprobJsonSchema: JSONSchema = convert(LogprobSchema);

export namespace Logprob {
  export function mergedList(a: Logprob[], b: Logprob[]): [Logprob[], boolean] {
    if (b.length === 0) {
      return [a, false];
    } else if (a.length === 0) {
      return [b, true];
    } else {
      return [[...a, ...b], true];
    }
  }
}

export const LogprobsSchema = z
  .object({
    content: z
      .array(LogprobSchema)
      .optional()
      .nullable()
      .describe("The log probabilities of the tokens in the content."),
    refusal: z
      .array(LogprobSchema)
      .optional()
      .nullable()
      .describe("The log probabilities of the tokens in the refusal."),
  })
  .describe("The log probabilities of the tokens generated by the model.");
export type Logprobs = z.infer<typeof LogprobsSchema>;
export const LogprobsJsonSchema: JSONSchema = convert(LogprobsSchema);

export namespace Logprobs {
  export function merged(a: Logprobs, b: Logprobs): [Logprobs, boolean] {
    const [content, contentChanged] = merge(
      a.content,
      b.content,
      Logprob.mergedList
    );
    const [refusal, refusalChanged] = merge(
      a.refusal,
      b.refusal,
      Logprob.mergedList
    );
    if (contentChanged || refusalChanged) {
      return [{ content, refusal }, true];
    } else {
      return [a, false];
    }
  }
}
