import z from "zod";

export const ResponseImageImageUrlSchema = z.object({
  type: z.literal("image_url"),
  image_url: z.object({
    url: z.string().describe("The Base64 URL of the generated image."),
  }),
});
export type ResponseImageImageUrl = z.infer<typeof ResponseImageImageUrlSchema>;

export const ResponseImageSchema = z
  .union([ResponseImageImageUrlSchema])
  .describe("An image generated by the model.");
export type ResponseImage = z.infer<typeof ResponseImageSchema>;

export namespace ResponseImage {
  export function mergedList(
    a: ResponseImage[],
    b: ResponseImage[]
  ): [ResponseImage[], boolean] {
    if (b.length === 0) {
      return [a, false];
    } else if (a.length === 0) {
      return [b, true];
    } else {
      return [[...a, ...b], true];
    }
  }
}
