import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://objective-ai.io";

  const staticRoutes = [
    "",
    "/functions",
    "/functions/create",
    "/profiles",
    "/profiles/train",
    "/ensembles",
    "/ensembles/create",
    "/ensemble-llms",
    "/ensemble-llms/create",
    "/chat",
    "/vector",
    "/people",
    "/information",
    "/faq",
    "/legal",
    "/sdk-first",
    "/vibe-native",
    "/account/keys",
    "/account/credits",
    "/legal/terms",
    "/legal/privacy",
    // API documentation pages
    "/docs/api/get/ensemble_llms",
    "/docs/api/get/ensemble_llms/id",
    "/docs/api/get/ensemble_llms/id/usage",
    "/docs/api/get/ensembles",
    "/docs/api/get/ensembles/id",
    "/docs/api/get/ensembles/id/usage",
    "/docs/api/get/functions",
    "/docs/api/get/functions/fowner/frepository/fcommit",
    "/docs/api/get/functions/fowner/frepository/fcommit/usage",
    "/docs/api/get/functions/fowner/frepository/fcommit/profiles/powner/prepository/pcommit",
    "/docs/api/get/functions/fowner/frepository/fcommit/profiles/powner/prepository/pcommit/usage",
    "/docs/api/get/functions/profiles",
    "/docs/api/get/functions/profiles/pairs",
    "/docs/api/get/functions/profiles/powner/prepository/pcommit",
    "/docs/api/get/functions/profiles/powner/prepository/pcommit/usage",
    "/docs/api/get/auth/credits",
    "/docs/api/get/auth/keys",
    "/docs/api/get/auth/keys/openrouter",
    "/docs/api/get/vector/completions/id",
    "/docs/api/get/vector/completions/cache",
    "/docs/api/post/functions",
    "/docs/api/post/functions/fowner/frepository/fcommit",
    "/docs/api/post/functions/fowner/frepository/fcommit/profiles/powner/prepository/pcommit",
    "/docs/api/post/functions/fowner/frepository/fcommit/profiles/compute",
    "/docs/api/post/functions/profiles/powner/prepository/pcommit",
    "/docs/api/post/functions/profiles/compute",
    "/docs/api/post/vector/completions",
    "/docs/api/post/chat/completions",
    "/docs/api/post/auth/keys",
    "/docs/api/post/auth/keys/openrouter",
    "/docs/api/delete/auth/keys",
    "/docs/api/delete/auth/keys/openrouter",
  ];

  return staticRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : 0.8,
  }));
}
