import z from "zod";
import { ObjectiveAI, RequestOptions } from "../client";
import { EnsembleSchema } from "./ensemble";

export const ListItemSchema = z.object({
  id: z.string().describe("The unique identifier for the Ensemble."),
});
export type ListItem = z.infer<typeof ListItemSchema>;

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Ensembles."),
});
export type List = z.infer<typeof ListSchema>;

export function list(
  client: ObjectiveAI,
  options?: RequestOptions,
): Promise<List> {
  return client.get_unary<List>("/ensembles", undefined, options);
}

export const RetrieveSchema = EnsembleSchema.extend({
  created: z
    .uint32()
    .describe("The Unix timestamp (in seconds) when the Ensemble was created."),
});
export type Retrieve = z.infer<typeof RetrieveSchema>;

export function retrieve(
  client: ObjectiveAI,
  id: string,
  options?: RequestOptions,
): Promise<Retrieve> {
  return client.get_unary<Retrieve>(`/ensembles/${id}`, undefined, options);
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe("The total number of requests made to this Ensemble."),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by this Ensemble.",
    ),
  prompt_tokens: z
    .uint32()
    .describe("The total number of prompt tokens sent to this Ensemble."),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Ensemble."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;

export function retrieveUsage(
  client: ObjectiveAI,
  id: string,
  options?: RequestOptions,
): Promise<HistoricalUsage> {
  return client.get_unary<HistoricalUsage>(
    `/ensembles/${id}/usage`,
    undefined,
    options,
  );
}
