import OpenAI from "openai";
import z from "zod";
import { EnsembleSchema } from "./ensemble";

export const ListItemSchema = z.object({
  id: z.string().describe("The unique identifier for the Ensemble."),
});
export type ListItem = z.infer<typeof ListItemSchema>;

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Ensembles."),
});
export type List = z.infer<typeof ListSchema>;

export async function list(
  openai: OpenAI,
  options?: OpenAI.RequestOptions
): Promise<List> {
  const response = await openai.get("/ensembles", options);
  return response as List;
}

export const RetrieveSchema = EnsembleSchema.extend({
  created: z
    .uint32()
    .describe("The Unix timestamp (in seconds) when the Ensemble was created."),
});
export type Retrieve = z.infer<typeof RetrieveSchema>;

export async function retrieve(
  openai: OpenAI,
  id: string,
  options?: OpenAI.RequestOptions
): Promise<Retrieve> {
  const response = await openai.get(`/ensembles/${id}`, options);
  return response as Retrieve;
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe("The total number of requests made to this Ensemble."),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by this Ensemble."
    ),
  prompt_tokens: z
    .uint32()
    .describe("The total number of prompt tokens sent to this Ensemble."),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Ensemble."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;

export async function retrieveUsage(
  openai: OpenAI,
  id: string,
  options?: OpenAI.RequestOptions
): Promise<HistoricalUsage> {
  const response = await openai.get(`/ensembles/${id}/usage`, options);
  return response as HistoricalUsage;
}
