import z from "zod";
import { ObjectiveAI, RequestOptions } from "../client";
import { EnsembleLlmSchema } from "./ensemble_llm";
import { convert, type JSONSchema } from "../json_schema";

export const ListItemSchema = z.object({
  id: z.string().describe("The unique identifier for the Ensemble LLM."),
});
export type ListItem = z.infer<typeof ListItemSchema>;
export const ListItemJsonSchema: JSONSchema = convert(ListItemSchema);

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Ensemble LLMs."),
});
export type List = z.infer<typeof ListSchema>;
export const ListJsonSchema: JSONSchema = convert(ListSchema);

export function list(
  client: ObjectiveAI,
  options?: RequestOptions,
): Promise<List> {
  return client.get_unary<List>("/ensemble_llms", undefined, options);
}

export const RetrieveSchema = EnsembleLlmSchema.extend({
  created: z
    .uint32()
    .describe(
      "The Unix timestamp (in seconds) when the Ensemble LLM was created.",
    ),
});
export type Retrieve = z.infer<typeof RetrieveSchema>;
export const RetrieveJsonSchema: JSONSchema = convert(RetrieveSchema);

export function retrieve(
  client: ObjectiveAI,
  id: string,
  options?: RequestOptions,
): Promise<Retrieve> {
  return client.get_unary<Retrieve>(`/ensemble_llms/${id}`, undefined, options);
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe("The total number of requests made to this Ensemble LLM."),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by this Ensemble LLM.",
    ),
  prompt_tokens: z
    .uint32()
    .describe("The total number of prompt tokens sent to this Ensemble LLM."),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Ensemble LLM."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;
export const HistoricalUsageJsonSchema: JSONSchema = convert(HistoricalUsageSchema);

export function retrieveUsage(
  client: ObjectiveAI,
  id: string,
  options?: RequestOptions,
): Promise<HistoricalUsage> {
  return client.get_unary<HistoricalUsage>(
    `/ensemble_llms/${id}/usage`,
    undefined,
    options,
  );
}
