//! Trait for fetching votes from historical completions.

use crate::ctx;

/// Fetches votes from a previously executed vector completion.
///
/// Only returns votes generated by actual LLM inference. Excludes votes that
/// came from the cache (`from_cache`) or random generation (`from_rng`), but
/// includes votes from previous retries.
#[async_trait::async_trait]
pub trait Fetcher<CTXEXT> {
    /// Retrieves votes from a historical vector completion by ID.
    ///
    /// Returns None if the completion is not found.
    async fn fetch(
        &self,
        ctx: ctx::Context<CTXEXT>,
        id: &str,
    ) -> Result<
        Option<Vec<objectiveai::vector::completions::response::Vote>>,
        objectiveai::error::ResponseError,
    >;
}
