//! Fetcher for votes from historical vector completions.
//!
//! Retrieves votes that were generated by actual LLM inference. Does not include
//! votes that came from the cache (`from_cache`) or random generation (`from_rng`),
//! but does include votes from previous retries.

mod fetcher;
mod objectiveai;

pub use fetcher::*;
pub use objectiveai::*;
