import z from "zod";
import { RoleSchema } from "../role";
import { ToolCallSchema } from "./tool_call";
import { ResponseImageSchema } from "../response_image";

export const MessageSchema = z
  .object({
    content: z.string().nullable().describe("The content of the message."),
    refusal: z.string().nullable().describe("The refusal message, if any."),
    role: RoleSchema,
    tool_calls: z
      .array(ToolCallSchema)
      .nullable()
      .describe("The tool calls made by the assistant, if any."),
    reasoning: z
      .string()
      .optional()
      .describe("The reasoning provided by the assistant, if any."),
    images: z
      .array(ResponseImageSchema)
      .optional()
      .describe("The images generated by the assistant, if any."),
  })
  .describe("A message generated by the assistant.");
