import OpenAI from "openai";
import z from "zod";

export const ListItemSchema = z.object({
  owner: z
    .string()
    .describe("The owner of the GitHub repository containing the function."),
  repository: z
    .string()
    .describe("The name of the GitHub repository containing the function."),
  commit: z
    .string()
    .describe(
      "The commit SHA of the GitHub repository containing the function."
    ),
});
export type ListItem = z.infer<typeof ListItemSchema>;

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Functions."),
});
export type List = z.infer<typeof ListSchema>;

export async function list(
  openai: OpenAI,
  options?: OpenAI.RequestOptions
): Promise<List> {
  const response = await openai.get("/functions", options);
  return response as List;
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe("The total number of requests made to this Function."),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by this Function."
    ),
  prompt_tokens: z
    .uint32()
    .describe("The total number of prompt tokens sent to this Function."),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Function."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;

export async function retrieveUsage(
  openai: OpenAI,
  fowner: string,
  frepository: string,
  fcommit: string | null | undefined,
  options?: OpenAI.RequestOptions
): Promise<HistoricalUsage> {
  const response = await openai.get(
    fcommit !== null && fcommit !== undefined
      ? `/functions/${fowner}/${frepository}/${fcommit}/usage`
      : `/functions/${fowner}/${frepository}/usage`,
    options
  );
  return response as HistoricalUsage;
}
