import z from "zod";
import { ObjectiveAI, RequestOptions } from "../client";
import {
  RemoteScalarFunctionSchema,
  RemoteVectorFunctionSchema,
} from "./function";
import {
  ListItemSchema as ProfileListItemSchema,
  RetrieveSchema as ProfileRetrieveSchema,
} from "./profiles/http";

export const ListItemSchema = z.object({
  owner: z
    .string()
    .describe("The owner of the GitHub repository containing the function."),
  repository: z
    .string()
    .describe("The name of the GitHub repository containing the function."),
  commit: z
    .string()
    .describe(
      "The commit SHA of the GitHub repository containing the function.",
    ),
});
export type ListItem = z.infer<typeof ListItemSchema>;

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Functions."),
});
export type List = z.infer<typeof ListSchema>;

export function list(
  client: ObjectiveAI,
  options?: RequestOptions,
): Promise<List> {
  return client.get_unary<List>("/functions", undefined, options);
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe("The total number of requests made to this Function."),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by this Function.",
    ),
  prompt_tokens: z
    .uint32()
    .describe("The total number of prompt tokens sent to this Function."),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Function."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;

export function retrieveUsage(
  client: ObjectiveAI,
  fowner: string,
  frepository: string,
  fcommit: string | null | undefined,
  options?: RequestOptions,
): Promise<HistoricalUsage> {
  const path =
    fcommit !== null && fcommit !== undefined
      ? `/functions/${fowner}/${frepository}/${fcommit}/usage`
      : `/functions/${fowner}/${frepository}/usage`;
  return client.get_unary<HistoricalUsage>(path, undefined, options);
}

export const RetrieveSchema = z.discriminatedUnion("type", [
  RemoteScalarFunctionSchema.extend(ListItemSchema.shape),
  RemoteVectorFunctionSchema.extend(ListItemSchema.shape),
]);
export type Retrieve = z.infer<typeof RetrieveSchema>;

export function retrieve(
  client: ObjectiveAI,
  fowner: string,
  frepository: string,
  fcommit: string | null | undefined,
  options?: RequestOptions,
): Promise<Retrieve> {
  const path =
    fcommit !== null && fcommit !== undefined
      ? `/functions/${fowner}/${frepository}/${fcommit}`
      : `/functions/${fowner}/${frepository}`;
  return client.get_unary<Retrieve>(path, undefined, options);
}

// Function-Profile Pairs

export const ListPairItemSchema = z.object({
  function: ListItemSchema.describe("The function."),
  profile: ProfileListItemSchema.describe("The profile."),
});
export type ListPairItem = z.infer<typeof ListPairItemSchema>;

export const ListPairsSchema = z.object({
  data: z
    .array(ListPairItemSchema)
    .describe("A list of Function-Profile pairs."),
});
export type ListPairs = z.infer<typeof ListPairsSchema>;

export function listPairs(
  client: ObjectiveAI,
  options?: RequestOptions,
): Promise<ListPairs> {
  return client.get_unary<ListPairs>(
    "/functions/profiles/pairs",
    undefined,
    options,
  );
}

export const RetrievePairSchema = z.object({
  function: RetrieveSchema.describe("The function."),
  profile: ProfileRetrieveSchema.describe("The profile."),
});
export type RetrievePair = z.infer<typeof RetrievePairSchema>;

export function retrievePair(
  client: ObjectiveAI,
  fowner: string,
  frepository: string,
  fcommit: string | null | undefined,
  powner: string,
  prepository: string,
  pcommit: string | null | undefined,
  options?: RequestOptions,
): Promise<RetrievePair> {
  let path = `/functions/${fowner}/${frepository}`;
  if (fcommit !== null && fcommit !== undefined) {
    path += `/${fcommit}`;
  }
  path += `/profiles/${powner}/${prepository}`;
  if (pcommit !== null && pcommit !== undefined) {
    path += `/${pcommit}`;
  }
  return client.get_unary<RetrievePair>(path, undefined, options);
}

export function retrievePairUsage(
  client: ObjectiveAI,
  fowner: string,
  frepository: string,
  fcommit: string | null | undefined,
  powner: string,
  prepository: string,
  pcommit: string | null | undefined,
  options?: RequestOptions,
): Promise<HistoricalUsage> {
  let path = `/functions/${fowner}/${frepository}`;
  if (fcommit !== null && fcommit !== undefined) {
    path += `/${fcommit}`;
  }
  path += `/profiles/${powner}/${prepository}`;
  if (pcommit !== null && pcommit !== undefined) {
    path += `/${pcommit}`;
  }
  path += "/usage";
  return client.get_unary<HistoricalUsage>(path, undefined, options);
}
