import OpenAI from "openai";
import z from "zod";

export const ListItemSchema = z.object({
  owner: z
    .string()
    .describe("The owner of the GitHub repository containing the profile."),
  repository: z
    .string()
    .describe("The name of the GitHub repository containing the profile."),
  commit: z
    .string()
    .describe(
      "The commit SHA of the GitHub repository containing the profile."
    ),
});
export type ListItem = z.infer<typeof ListItemSchema>;

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Functions."),
});
export type List = z.infer<typeof ListSchema>;

export async function list(
  openai: OpenAI,
  options?: OpenAI.RequestOptions
): Promise<List> {
  const response = await openai.get("/functions/profiles", options);
  return response as List;
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe(
      "The total number of requests made to Functions while using this Profile."
    ),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by Functions while using this Profile."
    ),
  prompt_tokens: z
    .uint32()
    .describe(
      "The total number of prompt tokens sent to Functions while using this Profile."
    ),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Profile."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;

export async function retrieveUsage(
  openai: OpenAI,
  powner: string,
  prepository: string,
  pcommit: string | null | undefined,
  options?: OpenAI.RequestOptions
): Promise<HistoricalUsage> {
  const response = await openai.get(
    pcommit !== null && pcommit !== undefined
      ? `/functions/profiles/${powner}/${prepository}/${pcommit}/usage`
      : `/functions/profiles/${powner}/${prepository}/usage`,
    options
  );
  return response as HistoricalUsage;
}
