import z from "zod";
import { ObjectiveAI, RequestOptions } from "../../client";
import { RemoteProfileSchema } from "../profile";
import { convert, type JSONSchema } from "../../json_schema";

export const ListItemSchema = z.object({
  owner: z
    .string()
    .describe("The owner of the GitHub repository containing the profile."),
  repository: z
    .string()
    .describe("The name of the GitHub repository containing the profile."),
  commit: z
    .string()
    .describe(
      "The commit SHA of the GitHub repository containing the profile.",
    ),
});
export type ListItem = z.infer<typeof ListItemSchema>;
export const ListItemJsonSchema: JSONSchema = convert(ListItemSchema);

export const ListSchema = z.object({
  data: z.array(ListItemSchema).describe("A list of Functions."),
});
export type List = z.infer<typeof ListSchema>;
export const ListJsonSchema: JSONSchema = convert(ListSchema);

export function list(
  client: ObjectiveAI,
  options?: RequestOptions,
): Promise<List> {
  return client.get_unary<List>("/functions/profiles", undefined, options);
}

export const HistoricalUsageSchema = z.object({
  requests: z
    .uint32()
    .describe(
      "The total number of requests made to Functions while using this Profile.",
    ),
  completion_tokens: z
    .uint32()
    .describe(
      "The total number of completion tokens generated by Functions while using this Profile.",
    ),
  prompt_tokens: z
    .uint32()
    .describe(
      "The total number of prompt tokens sent to Functions while using this Profile.",
    ),
  total_cost: z
    .number()
    .describe("The total cost incurred by using this Profile."),
});
export type HistoricalUsage = z.infer<typeof HistoricalUsageSchema>;
export const HistoricalUsageJsonSchema: JSONSchema = convert(HistoricalUsageSchema);

export function retrieveUsage(
  client: ObjectiveAI,
  powner: string,
  prepository: string,
  pcommit: string | null | undefined,
  options?: RequestOptions,
): Promise<HistoricalUsage> {
  const path =
    pcommit !== null && pcommit !== undefined
      ? `/functions/profiles/${powner}/${prepository}/${pcommit}/usage`
      : `/functions/profiles/${powner}/${prepository}/usage`;
  return client.get_unary<HistoricalUsage>(path, undefined, options);
}

export const RetrieveSchema = ListItemSchema.merge(RemoteProfileSchema);
export type Retrieve = z.infer<typeof RetrieveSchema>;
export const RetrieveJsonSchema: JSONSchema = convert(RetrieveSchema);

export function retrieve(
  client: ObjectiveAI,
  powner: string,
  prepository: string,
  pcommit: string | null | undefined,
  options?: RequestOptions,
): Promise<Retrieve> {
  const path =
    pcommit !== null && pcommit !== undefined
      ? `/functions/profiles/${powner}/${prepository}/${pcommit}`
      : `/functions/profiles/${powner}/${prepository}`;
  return client.get_unary<Retrieve>(path, undefined, options);
}
